M48
; DRILL file {KiCad 7.0.1} date Tue Feb 20 00:17:53 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-20T00:17:53-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0512
%
G90
G05
T1
X3.646Y-4.03
X3.646Y-4.2576
T2
X4.6514Y-3.9517
X4.6514Y-4.1485
T0
M30
